[package]
name = "nuc-build-led"
version = "0.1.0"
authors = ["Andrew Hunter <andrew@logicalshift.co.uk>"]

[dependencies]
tokio       = "0.1"
tokio-uds   = "0.1"
serde       = "^1.0.0"
futures     = "0.1"
